---
# Source: sn-platform/templates/streamnative-console/streamnative-console-initialize.yaml
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
apiVersion: batch/v1
kind: Job
metadata:
  name: "test-sn-platform-streamnative-console-init"
  namespace: pulsar
  labels:
    app: sn-platform
    chart: sn-platform-1.5.4
    release: test
    heritage: Helm
    cluster: test-sn-platform
    component: streamnative-console
spec:
  template:
    metadata:
      labels:
        app: sn-platform
        release: test
        cluster: test-sn-platform
    spec:
      initContainers:
        # This init container will wait for broker to be ready before
        # deploying the pulsar manager init job
        - name: wait-broker-ready
          image: "streamnative/sn-platform:2.9.2.17"
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c"]
          args:
            - >
              set -e; while [ "$(curl -s -o /dev/null -w '%{http_code}' http://test-sn-platform-broker:8080/status.html)" -ne "200" ]; do echo "pulsar cluster isn't initialized yet..."; sleep 5; done;
              echo "broker cluster is ready";
      containers:
      - name: "test-sn-platform-streamnative-console-init"
        image: "streamnative/sn-platform-console:v1.12.0"
        imagePullPolicy: IfNotPresent
        env:
        - name: SPRING_CONFIGURATION_FILE
          value: /pulsar-manager/pulsar-manager/application.properties
        - name: DEFAULT_ORGANIZATION
          value: streamnative
        - name: INSTANCE_NAME
          value: pulsar
        - name: WEB_SERVICE_URL
          value: http://test-sn-platform-broker.pulsar.svc.cluster.local:8080
        - name: KOP_SERVICE_URL
          value: test-sn-platform-broker.pulsar.svc.cluster.local:9092
        - name: STREAMNATIVE_CONSOLE_BACKEND_URL
          value: http://test-sn-platform-streamnative-console:7750
        - name: SUPER_USER_NAME
          value: admin
        - name: SUPER_USER_PASSWORD
          value: apachepulsar
        volumeMounts:
        - name: "test-sn-platform-streamnative-console-init-instance"
          mountPath: "/root/init_instance/"
        command: ["sh", "-c"]
        args:
          - >
            python3 /root/init_instance/init_instance.py 2>/dev/null;
            until [ $? -eq 0 ]; do
              echo "streamnative console is not ready now! wait another 10s~";
              sleep 10;
              python3 /root/init_instance/init_instance.py 2>/dev/null;
            done;
            echo "StreamNative Console is ready to use~";
            curl -sf -XPOST http://127.0.0.1:15020/quitquitquit || true;
      restartPolicy: Never
      serviceAccountName: test-sn-platform-streamnative-console-acct
      volumes:
        - name: "test-sn-platform-streamnative-console-init-instance"
          configMap:
            name: "test-sn-platform-streamnative-console-init-instance"
